# Generated by Django 2.1.2 on 2018-10-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181024_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={},
        ),
    ]
