# Generated by Django 2.1.2 on 2018-10-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_readnewstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNewsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'user_news_table',
                'managed': False,
            },
        ),
    ]
