# Generated by Django 2.1.2 on 2018-10-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_usernewstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingTable',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_content', models.TextField()),
            ],
            options={
                'db_table': 'testing_table',
                'managed': False,
            },
        ),
    ]
