# Generated by Django 2.1.2 on 2018-10-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_testingtable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernewstable',
            options={},
        ),
    ]
