# Generated by Django 2.1.2 on 2018-10-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20181028_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernewstable',
            options={'managed': False},
        ),
    ]
