# Generated by Django 2.1.2 on 2018-11-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_userscraptable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNewsTimeTable',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('reading_time', models.IntegerField()),
            ],
            options={
                'db_table': 'user_news_time_table',
                'managed': False,
            },
        ),
    ]
